import React, { Component } from 'react'
import { Content, TGTitle, TGDescription, TGDetail } from '../../components'

class HowItWorks extends Component {
  goToNext () {
    this.props.history.push('/WhitePaper')
  }

  goBack () {
    this.props.history.goBack()
  }

  render () {
    return (
      <Content>
        <TGTitle> Tailored risk exposure in the <br /> blockchain </TGTitle>
        <div style={styles.content}>
          <div style={styles.detail}>
            <TGDetail>
              Tokens will be issued that allow users to face the Nomisma foundation as a trustless counterparty, via smart contracts, to their desired cash flow / risk return profile. <br /><br />
              These tokens will cover transaction costs on the Ethereum blockchain and will embed a small fee per payoff structured and delivered and may entitle holders to the hedging gains generated by the replicating portfolios. <br /><br />
              Users can partake of analytics regarding the pricing of contingent claims on cryptocurrencies / coins. <br />
              Users will be able to generate any contingent claim, single and multiperiod one, facing the foundation. <br />
              For the prototype, users shall be able to define a desired a rate of return vs an acceptance of linear principal loss depending on a coin’s price performance during a specified time period. This will be priced in equilibrium against a claim that pays out a multiple of the original outlay in case of upside performance. <br /><br />
              We will thus be generating coin specific interest rate term structures across time as well as hazard rate / “riskiness” spread curves. <br />
              The end goal is the creation of fixed income claims for each coin.
            </TGDetail>
          </div>
        </div>
      </Content>
    )
  }
}

const styles = {
  content: {
    flex: 1,
    flexDirection: 'column'
  },
  description: {
    flex: 1
  },
  detail: {
    flex: 2
  },
  italic: {
    fontStyle: 'italic'
  }
}

export default HowItWorks
